config/routes.rb
Rails.application.routes.draw do
  get :login, to: 'sessions#new'
  get :logout, to: 'sessions#destroy'
  resources :sessions
  resources :users
  root to: 'users#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    redirect_to '/login' unless current_user
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by email: params[:email]
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to '/'
      flash[:notice] =  "logged in!!"
    else
      redirect_to '/login'
      flash[:alert] = "error: can't log in "
    end

  end

  def destroy
    session[:user_id] = nil
    redirect_to '/login'
    flash[:notice] = "logged out"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users= User.all
  end

  def new
    @user = User.new params[:user]
  end

  def create
    @user = User.new params_user
    if @user.save
      flash[:notice] = "Successfully created a user "
      redirect_to root_path
    else
      flash[:alert] = "A problem happened with user creation"
      render :new
    end
  end

  private

  def params_user
    params.require(:user).permit :name,:email, :password, :password_confirmation
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <%= content_tag :div, msg, :class => "flash_#{name}" %>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<ul class="nav">
  <li><%= link_to 'Home', root_path %></li>
  <%= render 'layouts/navigation_links' %>
</ul>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "User Authentication From Scratch" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "User Authentication From Scratch" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>

    <% if current_user %>
        Signed in as <%= current_user.name %> | <%= link_to "Logout", logout_path %>
    <% else %>
        <%= link_to 'Login', login_path %> | <%= link_to 'Signup', new_user_path %>
    <% end %>
    <main role="main">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </main>
  </body>
</html>

app/views/users/create.html.erb
<h1>User#create</h1>
<p>Find me in app/views/user/create.html.erb</p>

app/views/users/index.html.erb
<h1>Users</h1>

<% @users.each do |user| %>
  <%= user.name %>|<%= user.email %><br>
<% end %>

app/views/users/new.html.erb
<h1>User#new</h1>
<%= form_for @user do |f| %>

    <br />Name: <%= f.text_field :name %>
    <br />Email: <%= f.text_field :email %>
    <br />Password: <%= f.password_field :password %>
    <br />Password Confirmation: <%= f.password_field :password_confirmation %>
    <br /><%= f.submit "Submit" %>
<% end %>